### ISSUE TITLE
1.11.2 Support

### ISSUE THREAD

**Issue by Ristovski** [squeek502/Squake#12]
It looks like PlayerAPI has not been updated in a while and the mods creator has been inactive since the end of 2016.
Are there any plans to switch away from PlayerAPI or re-implement Squake in pure Forge?

**Comment by squeek502** [comment]
It'd definitely be nice to drop the PlayerAPI dependency. I'll look into it, but not sure exactly when.

**Comment by Ristovski** [comment]
I managed to compile PlayerAPI for 1.11.2 by changing the version specifier and recompiling (Source from [here](https://dl.dropboxusercontent.com/u/41082508/Minecraft/Modding/Player%20API/MC%201.10.2%20-%20Player%20API%20core%201.0.zip)). Could you look into this?

_Edit: So I fixed up the Squake code to work with 1.11 (mainly MathHelper methods and moveentity) but I can't make PlayerAPI work as a mod with Forge since it uses the old `DummyModContainer` or w/e. Any ideas?_

**Comment by squeek502** [comment]
PlayerAPI is a core mod so it needs some metadata added to its manifest for it to be loaded. If you're compiling with Gradle, add the following to your build.gradle:

```
jar {
	manifest {
		attributes 'FMLCorePlugin': 'api.player.forge.PlayerAPIContainer'
		attributes 'FMLCorePluginContainsFMLMod': 'false'
	}
}
```

**Comment by squeek502** [comment]
@Ristovski Had a go at porting to 1.11.2 and dropping the PlayerAPI dependency: https://github.com/squeek502/Squake/tree/1.11.2

From the commit message:
> Still some issues to work out, mainly "Player moved wrongly" when sneaking + jumping while going over a certain speed (surprisingly, this is not related to trimping, still happens if trimping is disabled)

Really not sure what's causing that at the moment; it could be something to do with the ASM or with a difference between 1.10 and 1.11 movement stuff.

**Comment by Ristovski** [comment]
Wow this is great. I will make sure to thoroughly test this out and see if I can figure out why that happens. Good work!

**Comment by Ristovski** [comment]
I think the `1.11` server added more movement checks as there now exists a `disableElytraMovementCheck` gamerule which disables movement checks server-side, **_only_** when the player has an Elytra equipped. 

This would suggest that either further checks have been set in place or the existing checks have been modified, in a way, that would explain why the `Player moved wrongly` occurs. I'll look into this tomorrow.

**Comment by Ristovski** [comment]
@squeek502 Any news on 1.12 support?

**Comment by squeek502** [comment]
One thing I've found is that the `player moved wrongly` error in 1.11.2 is a vanilla bug. Without Squake installed, you can still get the error by sprinting + jumping and then sneaking while landing.

It doesn't seem like this bug exists in 1.12 (but I'll need to port Squake to be sure), so it might be worth skipping 1.11.2 and going straight to 1.12.

**Comment by squeek502** [comment]
1.12 version released: https://github.com/squeek502/Squake/releases/tag/v1.0.4

Skipping 1.11.2 for now, as it seems like it'd be hard to track down the cause of the vanilla movement bug.

**Comment by Ristovski** [comment]
I was about to port it myself and submit a PR but you beat me to it :smile: 
Good job!
