### ISSUE TITLE
Unable To Swim In Lava 

### ISSUE THREAD

**Issue by Underqualified-Gunman** [squeek502/Squake#13]
the player behaves like they are inside of a block whilst  in lava when you jump you get above the lava source /flow you move a slight amount just a bug i noticed when i tried to enter my secret lava base

**Comment by squeek502** [comment]
I might know what's causing this, will look into fixing it.

**Comment by squeek502** [comment]
Should be fixed in 1.0.4: https://github.com/squeek502/Squake/releases/tag/v1.0.4
