### ISSUE TITLE
Update to 1.12.2

### ISSUE THREAD

**Issue by iamgreaser** [squeek502/Squake#16]
isCollidedHorizontally -> collidedHorizontally

Otherwise it's just a mc + forge + mapping version bump.

I think. I'm testing it right now in a definitely not clean MC mod environment. It's working.

**Comment by squeek502** [comment]
Whoops, forgot to push my 1.12.2 branch and upload the build to Github. I released a 1.12.2 version on Curseforge a little while back. Thanks for the reminder :+1:
