### ISSUE TITLE
Toggle Key

### ISSUE THREAD

**Issue by william-hollywood** [squeek502/Squake#17]
Hey,
I'd love to see a toggle key added to swap between bunny hopping and normal minecraft moving.
I play on a server with my friends and some dont like how its harder to climb ladders/pillar upwards because it keeps your horizontal move speed.
Is this possible to be added?
Thanks,
-ThatWDHGuy

**Comment by squeek502** [comment]
Two things:
- Ladder movement was meant to be unaffected, so that part is a bug that can be easily fixed (and will be).
- The toggle is still a good idea and is easy to implement. Will add that in a bit.

Sorry for not doing this way earlier; you actually requested the same thing a year ago as well (#11).

**Comment by squeek502** [comment]
Ladder bug fixed and toggle key added in v1.0.5:
https://minecraft.curseforge.com/projects/squake/files
https://github.com/squeek502/Squake/releases/tag/v1.0.5

@ThatWDHGuy I only added the toggle to the 1.10.x and 1.12 versions. Let me know if you play on an earlier Minecraft version and I'll backport the toggle key as necessary.

**Comment by freaky767** [comment]
i use this mod on 1.7.10 and i'd think its necessary because i play on lots of servers which have good anticheats and i dont want  risk myself getting banned

**Comment by squeek502** [comment]
@freaky767 the toggle was backported to 1.7.10: https://github.com/squeek502/Squake/issues/18

> Added a v1.0.5a version for 1.7.x with the toggle keybind:
> https://github.com/squeek502/Squake/releases/tag/v1.0.5
> https://minecraft.curseforge.com/projects/squake/files/2504931
