### ISSUE TITLE
Enable/Disable 1.7.10 (Backport pls)

### ISSUE THREAD

**Issue by william-hollywood** [squeek502/Squake#18]
Hi,
ThatWDHGuy here.
I play on 1.7.10 could you please make the enable and disable for it?
Thanks heaps <3
-WDH

**Comment by squeek502** [comment]
Added a v1.0.5a version for 1.7.x with the toggle keybind:
https://github.com/squeek502/Squake/releases/tag/v1.0.5
https://minecraft.curseforge.com/projects/squake/files/2504931
