### ISSUE TITLE
Turning doesn't match mouselook

### ISSUE THREAD

**Issue by Sozzer** [squeek502/Squake#19]
When moving the mouse, the direction of movement doesn't change until I look quite far away from my current direction. This seems to be related to the direction the player's body is facing, as when experimenting with the 3rd-person view I noticed that it wasn't when my head turned that I changed direction, but when my body turned. Unfortunately, I don't know much else about what might be causing the issue.

**Comment by squeek502** [comment]
I'm not sure I understand, and it's hard for me to tell if this is a bug or if it's a misunderstanding about how Quake movement works. What you described sounds somewhat normal for Quake-style movement (direction of movement in the air can only change gradually).

**Comment by Sozzer** [comment]
No no, it's not that the direction changes gradually, it's that I have to turn until I'm looking roughly at a 45 degree angle to the direction I'm moving before I can change it at _all._ Within that 90 degree cone in front of me, I can look around all I like to no avail. I can look off to the side, and I'll continue in the same direction forever. I've grabbed a quick capture of a few seconds, hopefully this helps clarify. While it is possibly a misunderstanding, it doesn't seem to match up to any videos I could find of squake in action.

https://i.gyazo.com/b541b5e106ab45dddd3104cec9a3b4bf.mp4
Let me know if that's not helpful enough, and I'll see if I can get something better.

**Comment by squeek502** [comment]
I'm assuming you're pressing forward in that clip, and not any of the strafe buttons. If so, then this is perfectly normal--on its own, your mouse does nothing to control your movement direction. Instead, you need to combine mouse movement with pressing the strafe button in the same direction that you are moving your mouse (and **not** pressing forward).

Here's the general sequence of events for bunnyhopping:
- Press forward to gain initial speed on the ground
- Jump
- Immediately let go of forward and press one of the strafe buttons
- Move your mouse gradually in the direction that you are strafing
- At this point you should be curving in that direction, and the speed you gain will depend on the speed/smoothness of your mouse movement (there's a sweet spot that you'll need to find by trial/error)
- To avoid just going in a circle, you'll need to periodically switch strafe directions (and at the same time, start gradually moving your mouse in the new strafe direction)
