### ISSUE TITLE
"Gliding" in unloaded chunks opening up the possibility for extreme TPS lag

### ISSUE THREAD

**Issue by floral-qua-floral** [squeek502/Squake#24]
If a player moves fast enough to fall into unloaded chunks (i.e. via TNT cannon, or during a server-side lag spike), they will retain all horizontal momentum. This allows the player to retain extreme speed and keep moving faster than the chunks can load, which could be a serious problem. Furthermore, depending on the mod's configuration, it can be really hard to lose this momentum, and so the player could end up gliding for quite some time. This is not only very inconvenient for the involved player, but puts a massive strain on the world as it fails to keep up with the fast-moving player. With a fairly barebones TNT cannon, I found myself displaced over a thousand blocks - I think I would have gone further, perhaps indefinitely, if I had not been in a Singleplayer game and therefore been able to pause the game to allow the world to load under me. The issue is severely compounded by a vanilla mechanic in which the effect of gravity is greatly reduced for players in unloaded chunks, which prolonged the flight significantly.

Some proposed solutions are to deaccelerate players who are in unloaded chunks, to cancel all their horizontal momentum, or alternatively to just "freeze" their momentum to bring them to a stop and then restore it once the chunks are loaded.

**Comment by squeek502** [comment]
This sounds out-of-scope for this mod, as going too fast is not a problem unique to this mod.
