### ISSUE TITLE
Tinker's Construct Slime Boots

### ISSUE THREAD

**Issue by Setadokalo** [squeek502/Squake#27]
The slime boots from TC cause a... *slight* increase in the effectiveness of bunny hop air strafing. The speed increase shifts dramatically, from ~2% max to continuous >20% increase in speed, quickly reaching over 50m/s and causing the server to cancel all momentum.

(I know the mod is pretty much dead, but wishful thinking)

**Comment by squeek502** [comment]
Duplicate of https://github.com/squeek502/Squake/issues/10
