### ISSUE TITLE
How Do I Compile The 1.16.4 Branch

### ISSUE THREAD

**Issue by ZeldaTakahiro** [squeek502/Squake#29]
Its a stupid question but yah i have no clue on how to compile the code to make it a usable mod

**Comment by squeek502** [comment]
As long as you have a JDK installed, then cloning the branch and running `./gradlew build` from inside the cloned directory should work.

If you plan to make changes, then you'd want to follow the steps here: https://fabricmc.net/wiki/tutorial:setup

**Comment by ZeldaTakahiro** [comment]
Sorry for responding late but thanks!
