### ISSUE TITLE
This is more like a discussion post than an issue, but you don't have discussions enabled.

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [squeek502/Squake#30]
Sorry, I was just wondering where the actual jar file is once you run the gradlew.bat.

Again, sorry I'm posting this in issues, I just don't know how else to communicate with you guys.

**Comment by squeek502** [comment]
Typically in `build/libs/`

Just enabled discussions as well btw.

**Comment by BeansBeefBroccoli** [comment]
ok, thank you
