### ISSUE TITLE
Unable to build sucsessfully

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [squeek502/Squake#32]
I am using gradlew.bat build, but when I try it says BUILD FAILED

do I call it a [log](https://paste.ee/p/rN3KB)?

Edit: I don't know how, but I forgot to say I'm using the 1.16 fabric version

**Comment by squeek502** [comment]
Yeah, that branch is still a work-in-progress, hence why it's not been released. That specific errors looks like it's caused by the wrong import being included.

**Comment by BeansBeefBroccoli** [comment]
ok, is it possible for me to fix it, or do I just have to wait, it's fine if I have to wait, I'm just wondering.
