### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by william-hollywood** [squeek502/Squake#6]
Fall Damage is broken in the latest version. You die after falling from 6 1/2 blocks high. normal death after falling comes at ~24 blocks. Plus in the config the "fallDistanceThresholdIncrease" has little to no effect on this.

**Comment by squeek502** [comment]
Thanks for reporting it here, I still need to look into this.

**Comment by squeek502** [comment]
@ThatWDHGuy really late, but the latest 1.8+ versions _should_ fix this. Let me know if you run into any issues with it.

**Comment by william-hollywood** [comment]
Thx. i'll try them out
